### ISSUE TITLE
Survivor Sheet: move meta info and controls to modal

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#229]
Things it could show at the top:

- [x] years as a departing/returning survivor
- [x] users who have favorited the survivor
- [x] created on, created by, etc.
- [x] born in ly

Beneath that, all of this:

![survivorjunk](https://user-images.githubusercontent.com/48043/30458092-affa44ba-996f-11e7-8480-3810464a2e6a.png)

**Comment by toconnell** [comment]
This is (finally) going out in the next release. Closing it now.
