### ISSUE TITLE
Survivor: API-side normalize() enhancements to-do list

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#251]
We need to start normalizing/baselining Survivor MDB data in the API. To-do list:

- [x] add 'meta' key to the main MDB doc
- [x] convert A&Is
- [x] convert FA's
- [x] convert Disorders
- [x] build a method to enforce game asset biz-logic (e.g. 'partner_id' and the 'partner' A&I, etc.) at the end of normalization
- [x] add campaign-specific attribute keys (if not present)
- [x] convert campaign-specific attribute names to handles
- [x] convert 'favorite' from a bool to a list
- [x] convert epithets
- [x] convert 'public' to a bool (normalize)

**Comment by toconnell** [comment]
A&I conversion is a go:

![screen shot 2017-07-06 at 09 53 20 am](https://user-images.githubusercontent.com/48043/27917440-97e93a2c-6231-11e7-8bf2-08b08015bdbc.png)

**Comment by toconnell** [comment]
This got handled a few releases ago and I forgot to close the ticket. I think  2.44.n had this actually.
