### ISSUE TITLE
Survivor Sheet: modal/fixed overlay for temporary stat adjustment that replaces existing controls and facilitates tracking buffs from tokens, gear, etc.

### ISSUE THREAD

**Issue by toconnell** [toconnell/kdm-manager#33]
Lay some pop-up/modal controls over the survivor sheet that replace the attribute adjustment controls.

Basically, steal the design from the Google Sheet below and replace the attribute controls with it. 

This should probably be its own milestone/release.

From DT:

> I would just like to see additional boxes on the survivor screen to manage stat modifiers (whether from gear or tokens). Users would still need to use physical gear grids and cards, but total survivor stats could be tracked in the app and referred to at a glance without confusing which modifiers are temporary, gear based, or permanent. 
> 
> Users fill in the stat modifiers in the lower table when gained, and the combined stats are tracked in the upper table. That way, temporary and gear-based stat modifiers can be easily identified and zeroed out when the survivor returns from a hunt. There could even be a button somewhere on each survivor sheet labeled "remove gear," but that's not strictly necessary (just time-saving)

![](http://cf.geekdo-images.com/images/pic3158082_md.jpg)

- [x] Create the overlay
- [x] Remove the old controls/buttons for base stat adjustment
- [x] Style it for mobile
- [x] Style it for tablet
- [x] Style it for wide
- [x] Create survivor update methods
- [x] Do no-refresh form submissions on any refresh() call
- [x] Update the survivor record and flash the "SAVED!" button without a page refresh
- [x] Update kdmManager.js

**Comment by toconnell** [comment]
I'm currently thinking that this wants to be some kind of fixed/floating overlay on the survivor sheet that adds some additional controls for Tokens, kind of like this:

![token_overlay_mockup](https://cloud.githubusercontent.com/assets/48043/20435179/c245be74-ad70-11e6-9c0d-f57c0ae3bb79.jpg)

**Comment by toconnell** [comment]
Glorious
